name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  bats:
    name: Bats tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bats
        uses: bats-core/bats-action@e412797c46257a2dbf3775f6f6010b33ee6cb99f # v3.0.1

      - name: Run all bats tests
        run: bats tests/formats/ tests/scripts/
